### PR TITLE
NAV-12: remove .open class in exchange for aria-expanded

### LINKED ISSUE #12: Buttons need to toggle the aria expanded attribute
Buttons should toggle https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded and CSS should use that attribute within selector

### PR DESCRIPTION
**Pull request by claireristow**
Fixes #12

### CODE REVIEW

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr14-me8mojlbjsmlkotzazjz7fjqmf8n7c4g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a5c795dc23a4c5536d2e56

**Comment by mherchel** [comment]
First glance, this looks correct. Can you update this to use PostCSS?

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr14-me8mojlbjsmlkotzazjz7fjqmf8n7c4g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a5c795dc23a4c5536d2e56

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr14-me8mojlbjsmlkotzazjz7fjqmf8n7c4g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a5c795dc23a4c5536d2e56

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr14-me8mojlbjsmlkotzazjz7fjqmf8n7c4g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a5c795dc23a4c5536d2e56

**Pull request merged**
