### PR TITLE
NAV-28: postcss updates

### LINKED ISSUE #10: Set up PostCSS and add documentation
Bring in core’s postcss-reset-env and install the [required plugins](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/scripts/css/compile.js) (add link from above)

### PR DESCRIPTION
**Pull request by claireristow**
**This PR addresses the following:** 
- copy over postCSS setup from drupal core
- add nesting to css
- add local setup instructions to readme

Fixes #10 

**Questions:**
Should we have the generated `.css` files in a separate folder so there is no confusion about which files should be updated by developers (only `.pcss.css` files)? 

Link to test: https://pr13-hksyhzv9c9whel2lp60f7uotmmnxtpej.tugboatqa.com/

### CODE REVIEW

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr13-hksyhzv9c9whel2lp60f7uotmmnxtpej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a5a199757563ca3764921b

**Comment by mherchel** [comment]
Let me know when this is ready for review @claireristow (I see you're still pushing commits?)

> Should we have the generated .css files in a separate folder so there is no confusion about which files should be updated by developers (only .pcss.css files)?

Nope! Same directory :D

**Comment by claireristow** [comment]
@mherchel alrighty, same directory it is! And yes, this is ready for your review now :)

**Comment by mherchel** [comment]
Looks great!

**Pull request merged**
