### PR TITLE
#9 sticky user section

### PR DESCRIPTION
**Pull request by sveta1x**

### CODE REVIEW

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Comment by ckrina** [comment]
Nice job using CSS :D
Playing a little bit with it I found 2 things that maybe you can come up with solutions for:
1. Minimum height for the whole toolbar: if you make the screen super small the sticky region gets on top of the close element. I know it's a really edge case, but it would be great to have a solution in place.
2. Maybe there is a way to add some king of visual delimitation between the sticky region and the rest of the toolbar because otherwise it's a bit confusing. Ideally, I'd go with a shadow that appears only when there is something below, but it might be complicated. So at least I'd try to add a light top border for now. Fel free to choose the solution you feel more comfortable with.

Also, feel free to merge this and work in another PR for the follow-ups so we can avoid conficts.

**Review by ckrina — APPROVED** [review]

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Comment by sveta1x** [comment]
> Nice job using CSS :D Playing a little bit with it I found 2 things that maybe you can come up with solutions for:
> 
> 1. Minimum height for the whole toolbar: if you make the screen super small the sticky region gets on top of the close element. I know it's a really edge case, but it would be great to have a solution in place.
> 2. Maybe there is a way to add some king of visual delimitation between the sticky region and the rest of the toolbar because otherwise it's a bit confusing. Ideally, I'd go with a shadow that appears only when there is something below, but it might be complicated. So at least I'd try to add a light top border for now. Fel free to choose the solution you feel more comfortable with.
> 
> Also, feel free to merge this and work in another PR for the follow-ups so we can avoid conficts.

1. I added min-height as you said but used media query for max-height 300px. I would also remove sticky position for this edge case and some margin-top as well. Then user could see menu better. 

2. Added border and box-shadow similar to the design 

Please check again

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Comment by starshaped** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr27-dcorqweoxnctiwctu3ternqr4hbnfx4z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a6d434ee74754fca84eb4d

**Review by ckrina — APPROVED** [review]

**Comment by ckrina** [comment]
Thanks @sveta1x ! Merging this.

**Pull request merged**
